<?php
/**
 * @file
 * Code for the categorized module.
 */

/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function categorized_theme($existing, $type, $theme, $path) {
  return array(
    'categorized_block' =>
      array(
        'variables' => array(
          'description' => 'description',
          'categories' => 'categories',
          'terms' => 'terms'
        ),
        'template' => 'block--categorized_block',
      )
  );
}
